[build]
command = "npm run build"
output_directory = "out"

[site]
bucket = "out"
exclude = [
  "node_modules/**/*",
  ".git/**/*",
  ".github/**/*"
]

[build.environment]
NODE_VERSION = "16"
NPM_VERSION = "8" 